### ISSUE TITLE
Pause doesn't show on Android

### ISSUE THREAD

**Issue by williamfridh** [PontusAhlin/HorrorGame#60]
When pressing pause on Android, the pause menu doesn't show, but everything is disabled.

**Comment by PH77SER** [comment]
findings: 
- this bug is only in the entrance scene, for some reason
- this cannot be recreated in the editor, only in live. you can replicate a similar situation by returning to menu and then going back ingame and pressing pause
- it looks like the pause menu is getting enabled but it isnt being displayed on canvas for some bizzare reason
- good luck

**Comment by williamfridh** [comment]
The bug can also be recreated by entering the game via the entrance scene, going into the asylum and die/escape, then go start a new game.

**Comment by williamfridh** [comment]
This is now fixed. Turns out it was simply a hierarchy issue in Unity.
